apiVersion: v1
kind: ConfigMap
metadata:
  name: ftservices-configmap
data:
  mysql_host: mysql-service
  nginx_host: nginx-service
  wordpress_host: wordpress-service
  phpmyadmin_host: phpmyadmin-service
  influxdb_host: influxdb-service
  minikube_ip: 192.168.49.2
