apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps-storage
        persistentVolumeClaim:
          claimName: task-pv-claim-ftps
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: "/home/ftp"
          name: ftps-storage
        ports:
        - name: ftps
          containerPort: 21
        - name: ftps-pasv
          containerPort: 50000
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /root/liveness.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        - name: ENV_TELEGRAF_INFLUXDB_USR_PWD
          valueFrom:
            secretKeyRef:
              name: ftservices-secret
              key: telegraf_influxdb_usr_pwd
        - name: ENV_TELEGRAF_INFLUXDB_USR
          valueFrom:
            secretKeyRef:
              name: ftservices-secret
              key: telegraf_influxdb_usr
        - name: ENV_TELEGRAF_INFLUXDB_NAME
          valueFrom:
            secretKeyRef:
              name: ftservices-secret
              key: telegraf_influxdb_db
        - name: ENV_INFLUXDB_HOST
          valueFrom:
            configMapKeyRef:
              name: ftservices-configmap
              key: influxdb_host
        - name: ENV_MINIKUBE_HOST
          valueFrom:
            configMapKeyRef:
              name: ftservices-configmap
              key: minikube_ip
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
    - name: ftps-pasv
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: LoadBalancer
